baseURL = "https://slymanmrcan.github.io/Blog/"
relativeURLs = false
locale = "tr"
defaultContentLanguage = "tr"
title = "Suleyman Mercan"

timeZone = "UTC"
ignoreFiles = ["\\.DS_Store$"]

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  tagline = "Neon analog notlar ve uzun hikâyeler."
  description = "Teknoloji tarihi, siber güvenlik ve internet kültürü üzerine Türkçe uzun format yazılar."

[menu]
  [[menu.main]]
    name = "Ana Sayfa"
    url = ""
    weight = 1
  [[menu.main]]
    name = "Yazılar"
    url = "posts/"
    weight = 2

# Uncomment to enable multi-language structure.
# [languages]
#   [languages.en]
#     languageName = "English"
#     weight = 1
#   [languages.tr]
#     languageName = "Turkish"
#     weight = 2
